Fixes issue redirect to home
gargmegham/ShieldPeer pull request #8
Opened 2024-06-20 16:12 UTC by Thewhite33

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

-   [ ] Test A
-   [ ] Test B

**Test Configuration**:

-   Firmware version:
-   Hardware:
-   Toolchain:
-   SDK:

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

2024-06-20 16:30 UTC, gargmegham commented on src/components/ui/navbar.tsx
> +            link: "/home#demo",
Just change it to `/home` and I'll merge it in

2024-06-20 16:30 UTC, gargmegham requested changes
Just change it to `/home` and I'll merge it in

2024-06-20 17:38 UTC, Thewhite33 commented
If I give only /home then demo page will not work so I chosed /home#demo

2024-06-20 17:43 UTC, gargmegham commented
> If I give only /home then demo page will not work so I chosed /home#demo

Your fix is not working, check out deployed preview https://vercel.live/open-feedback/shield-peer-git-fork-thewhite33-fixes-7-redi-04f3d2-megham-garg.vercel.app?via=pr-comment-visit-preview-link&passThrough=1

2024-06-20 17:52 UTC, gargmegham commented
Before raising pull requests, please test your changes on local.

Do read the contributing guidelines and follow `.github/PULL_REQUEST_TEMPLATE.md` for PR description

2024-06-20 18:11 UTC, Thewhite33 commented
I checked locally it worked fine there but it's not working now I will update this.
Apologies

2024-06-21 14:19 UTC, gargmegham approved these changes
LGTM
![Screenshot 2024-06-21 at 7 48 10 PM](https://github.com/gargmegham/ShieldPeer/assets/95271253/2cb33926-eee1-4aa5-9a42-c6b8d6260613)

2024-06-21 14:19 UTC, merged